name: 'Automatic pull request review'
description: 'GH action to pull requests only for dev'
author: 'saurabhk>'
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'thumbs-up'
  color: 'gray-dark'
inputs:
  event:
    description: 'The event to perform on the pull request review.'
    default: 'APPROVE'
  body:
    description: 'The contents of the review body comment. Required when event is COMMENT or REQUEST_CHANGES.'
